#!/bin/sh
if device=`ip route show | grep default | grep -o '[a-z]\+[0-9]'`;
then
    ip=`ip route | grep -o 'src [0-9.]\+' | grep -o '[0-9.]\+'`

    if test "$device" == "wlan0";
    then
        essid=`iwconfig wlan0 | grep -o '"[-a-z0-9]\+"' | grep -o '[-a-z0-9]\+'`
        rate=`iwlist wlan0 rate | grep -o '[0-9.]\+\( Mb/s\)'`
        echo "WIFI: $essid ($rate) IP: $ip"
    else
        echo "LAN: $ip"
    fi
else
    echo "<fc=#FF0000>Network Not Connected</fc>"
fi
