#!/bin/sh
if   ip=`ifconfig eth0 | grep -o 'inet [0-9.]\+' | grep -o '[0-9.]\+'`
then
    echo "LAN: $ip"
elif   ip=`ifconfig wlan0 | grep -o 'inet [0-9.]\+' | grep -o '[0-9.]\+'`
then
    essid=`iwconfig wlan0 | grep -o '"[-a-zA-Z0-9]\+"' | grep -o '[-a-zA-Z0-9]\+'`
    rate=`iwlist wlan0 rate | grep -o '[0-9.]\+\( Mb/s\)'`
    echo "WIFI: $essid ($rate) IP: $ip"
else
    echo "<fc=#FF0000>Network Not Connected</fc>"
fi
