#!/bin/sh
if   ip=`ifconfig eth0 | grep -o 'inet [0-9.]\+' | grep -o '[0-9.]\+'`
then
    echo "<fc=#0099CC>LAN:</fc> $ip"
elif   ip=`ifconfig wlan0 | grep -o 'inet [0-9.]\+' | grep -o '[0-9.]\+'`
then
    essid=`iwconfig wlan0 | grep -o '"[-a-zA-Z0-9_]\+"' | grep -o '[-a-zA-Z0-9_]\+'`
    rate=`iwlist wlan0 rate | grep -o '[0-9.]\+\( Mb/s\)'`
    echo "<fc=#0099CC>WIFI:</fc> $essid ($rate) <fc=#0099CC>IP:</fc> $ip"
else
    echo "<fc=#E00000>NO NETWORK CONNECTION</fc>"
fi
